'use client';

import { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle, Loader2, Pencil, Trash2, UserPlus, X } from 'lucide-react';

interface Member { id: string; name: string; email: string; role: string; oabNumber?: string; phone?: string; active: boolean; }
const emptyForm = { name: '', email: '', password: '', role: 'LAWYER', oabNumber: '', phone: '' };
const roles = [{ value: 'LAWYER', label: 'Advogado(a)' }, { value: 'OFFICE_ADMIN', label: 'Administrador' }, { value: 'STAFF', label: 'Secretária / Colaborador' }, { value: 'VIEWER', label: 'Visualizador' }];

export default function TeamPage() {
  const [members, setMembers] = useState<Member[]>([]); const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false); const [editing, setEditing] = useState<Member | null>(null); const [deleting, setDeleting] = useState<Member | null>(null);
  const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const fetchTeam = async () => { setLoading(true); try { const data = await (await fetch('/api/office/team')).json(); setMembers(data.members || []); } finally { setLoading(false); } };
  useEffect(() => { void fetchTeam(); }, []);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setError(''); setShowModal(true); };
  const openEdit = (member: Member) => { setEditing(member); setForm({ name: member.name, email: member.email, password: '', role: member.role, oabNumber: member.oabNumber || '', phone: member.phone || '' }); setError(''); setShowModal(true); };
  const closeModal = () => { setShowModal(false); setEditing(null); setError(''); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const res = await fetch('/api/office/team', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { id: editing.id, ...form } : form) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Não foi possível salvar o acesso.'); closeModal(); await fetchTeam(); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; setSaving(true); setError(''); try { const res = await fetch(`/api/office/team?id=${deleting.id}`, { method: 'DELETE' }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Não foi possível excluir o acesso.'); setDeleting(null); await fetchTeam(); } catch (err: any) { setError(err.message); } finally { setSaving(false); } };
  const badge = (role: string) => <span className={`px-2.5 py-1 rounded-full font-bold text-xs ${role === 'OFFICE_ADMIN' ? 'bg-[#0B1D3D] text-gold-400' : role === 'LAWYER' ? 'bg-blue-50 text-blue-700 border border-blue-200' : role === 'VIEWER' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-700'}`}>{roles.find((item) => item.value === role)?.label || role}</span>;
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#0B1D3D] tracking-tight">Gestão da Equipe do Escritório</h1><p className="text-sm text-slate-500 mt-1">Gerencie acessos individuais, cargos e dados profissionais.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-gold-500 hover:bg-gold-400 text-[#0B1D3D] font-bold rounded-xl shadow-sm text-sm"><UserPlus className="w-4 h-4" />Adicionar membro</button></div>
    <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">{loading ? <div className="p-12 text-center text-slate-400 text-sm"><Loader2 className="w-4 h-4 animate-spin inline mr-2" />Carregando equipe...</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm text-slate-700"><thead className="bg-slate-50 border-b text-xs font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-3.5">Membro</th><th className="px-6 py-3.5">Acesso</th><th className="px-6 py-3.5">OAB</th><th className="px-6 py-3.5">Contato</th><th className="px-6 py-3.5 text-right">Gestão</th></tr></thead><tbody className="divide-y divide-slate-100">{members.map((member) => <tr key={member.id} className="hover:bg-slate-50/80"><td className="px-6 py-4"><p className="font-bold text-slate-900">{member.name}</p><p className="text-xs text-slate-400">{member.email}</p></td><td className="px-6 py-4">{badge(member.role)}</td><td className="px-6 py-4 font-mono text-xs">{member.oabNumber || '—'}</td><td className="px-6 py-4 text-xs">{member.phone || '—'}</td><td className="px-6 py-4"><div className="flex justify-end gap-2"><span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600"><CheckCircle className="w-3.5 h-3.5" />Ativo</span><button onClick={() => openEdit(member)} title="Editar membro" className="p-2 rounded-lg border border-blue-200 text-blue-700 hover:bg-blue-50"><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => { setDeleting(member); setError(''); }} title="Excluir membro" className="p-2 rounded-lg border border-rose-200 text-rose-700 hover:bg-rose-50"><Trash2 className="w-3.5 h-3.5" /></button></div></td></tr>)}</tbody></table></div>}</div>
    {showModal && <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><form onSubmit={save} className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl"><div className="flex justify-between border-b pb-4"><div><h2 className="font-bold text-[#0B1D3D]">{editing ? 'Editar acesso da equipe' : 'Novo membro da equipe'}</h2><p className="text-xs text-slate-500 mt-1">{editing ? 'Altere dados, cargo ou a senha de acesso.' : 'Crie um login individual para o escritório.'}</p></div><button type="button" onClick={closeModal}><X className="text-slate-400" /></button></div>{error && <p className="mt-4 p-3 bg-rose-50 text-rose-700 rounded-xl text-xs"><AlertCircle className="w-4 h-4 inline mr-1" />{error}</p>}<div className="mt-4 space-y-3 text-sm"><label className="block">Nome completo *<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full p-2.5 border rounded-xl" /></label><label className="block">E-mail *<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full p-2.5 border rounded-xl" /></label><label className="block">{editing ? 'Nova senha (opcional)' : 'Senha de acesso *'}<input required={!editing} minLength={form.password ? 6 : undefined} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder={editing ? 'Deixe em branco para manter a atual' : 'Mínimo 6 caracteres'} className="mt-1 w-full p-2.5 border rounded-xl" /></label><div className="grid grid-cols-2 gap-3"><label>Cargo *<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="mt-1 w-full p-2.5 border rounded-xl">{roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label>OAB<input value={form.oabNumber} onChange={(e) => setForm({ ...form, oabNumber: e.target.value })} className="mt-1 w-full p-2.5 border rounded-xl" /></label></div><label className="block">Telefone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="mt-1 w-full p-2.5 border rounded-xl" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={closeModal} className="px-4 py-2 text-sm">Cancelar</button><button disabled={saving} className="px-5 py-2.5 bg-[#0B1D3D] text-white font-bold rounded-xl text-sm disabled:opacity-50">{saving ? 'Salvando...' : editing ? 'Salvar alterações' : 'Cadastrar membro'}</button></div></form></div>}
    {deleting && <div className="fixed inset-0 z-[60] bg-black/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl"><h2 className="font-bold text-[#0B1D3D]">Excluir acesso?</h2><p className="mt-2 text-sm text-slate-600">Deseja remover <strong>{deleting.name}</strong>? O histórico já vinculado será preservado.</p>{error && <p className="mt-3 text-xs text-rose-700 font-bold">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button onClick={() => setDeleting(null)} className="px-4 py-2 text-sm">Cancelar</button><button onClick={remove} disabled={saving} className="px-5 py-2.5 bg-rose-600 text-white font-bold rounded-xl text-sm">{saving ? 'Excluindo...' : 'Excluir acesso'}</button></div></div></div>}
  </div>;
}
