'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { AlertTriangle, BriefcaseBusiness, CalendarDays, CheckCircle2, Download, FileText, FolderPlus, Loader2, Pencil, Search, User, X } from 'lucide-react';

type Activity = { id: string; type: string; description: string; createdAt: string };
type Process = { id: string; title: string; legalArea?: string; status: string; priority: string; dueDate?: string | null; processNumber?: string; protocolNumber?: string; notes?: string; lastActivityAt: string; client: { id: string; name: string; cpfCnpj: string; phone?: string }; documents: Array<{ id: string; title: string; status: string; signedFileId?: string }>; activities: Activity[] };
type Client = { id: string; name: string; cpfCnpj: string };
const statuses = [{ id: 'EM_TRIAGEM', label: 'Triagem' }, { id: 'DOCUMENTACAO_PENDENTE', label: 'Documentação pendente' }, { id: 'PRONTO_PARA_PROTOCOLAR', label: 'Pronto para protocolar' }, { id: 'PROTOCOLADO', label: 'Protocolado' }, { id: 'EM_ANDAMENTO', label: 'Em andamento' }, { id: 'CONCLUIDO', label: 'Concluído / arquivado' }];
const priorities = [{ id: 'ALTA', label: 'Alta', color: 'bg-rose-100 text-rose-700' }, { id: 'NORMAL', label: 'Normal', color: 'bg-blue-100 text-blue-700' }, { id: 'BAIXA', label: 'Baixa', color: 'bg-slate-100 text-slate-600' }];
const blankForm = { clientId: '', title: '', legalArea: 'Previdenciário', status: 'EM_TRIAGEM', priority: 'NORMAL', dueDate: '', processNumber: '', protocolNumber: '', notes: '', documentIds: [] as string[] };

export default function ProcessosPage() {
  const searchParams = useSearchParams(); const openedFromDocuments = useRef(false);
  const [processes, setProcesses] = useState<Process[]>([]); const [clients, setClients] = useState<Client[]>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [selected, setSelected] = useState<Process | null>(null); const [editing, setEditing] = useState(false); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('ALL'); const [form, setForm] = useState(blankForm); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); const [p, c] = await Promise.all([fetch('/api/processos').then(r => r.json()), fetch('/api/clients').then(r => r.json())]); setProcesses(p.processes || []); setClients(c.clients || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  useEffect(() => { const clientId = searchParams.get('clienteId'); if (!clientId || openedFromDocuments.current) return; openedFromDocuments.current = true; setForm(current => ({ ...current, clientId, documentIds: (searchParams.get('documentoIds') || '').split(',').filter(Boolean) })); setModal(true); }, [searchParams]);
  const visible = useMemo(() => processes.filter(p => (statusFilter === 'ALL' || p.status === statusFilter) && `${p.title} ${p.client.name} ${p.processNumber || ''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))), [processes, statusFilter, query]);
  const overdue = (p: Process) => !!p.dueDate && p.status !== 'CONCLUIDO' && new Date(p.dueDate).getTime() < new Date().setHours(0,0,0,0);
  const create = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); const r = await fetch('/api/processos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); setSaving(false); if (!r.ok) return alert(d.error); setModal(false); setForm(blankForm); await load(); };
  const saveEdit = async (e: React.FormEvent) => { e.preventDefault(); if (!selected) return; setSaving(true); const r = await fetch(`/api/processos/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); setSaving(false); if (!r.ok) return alert(d.error); setEditing(false); setSelected(null); setForm(blankForm); await load(); };
  const beginEdit = (p: Process) => { setForm({ clientId: p.client.id, title: p.title, legalArea: p.legalArea || '', status: p.status, priority: p.priority || 'NORMAL', dueDate: p.dueDate ? new Date(p.dueDate).toISOString().slice(0, 10) : '', processNumber: p.processNumber || '', protocolNumber: p.protocolNumber || '', notes: p.notes || '', documentIds: [] }); setEditing(true); };
  const statusLabel = (id: string) => statuses.find(s => s.id === id)?.label || id; const priority = (id: string) => priorities.find(p => p.id === id) || priorities[1];
  const ProcessForm = ({ edit }: { edit?: boolean }) => <form onSubmit={edit ? saveEdit : create} className="space-y-3"><div className="grid md:grid-cols-2 gap-3"><select required disabled={!!edit} value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })} className="w-full border rounded-xl p-3 text-sm bg-white"><option value="">Selecione a cliente</option>{clients.map(c => <option key={c.id} value={c.id}>{c.name} — {c.cpfCnpj}</option>)}</select><input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Título do atendimento" className="border rounded-xl p-3 text-sm" /></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><input value={form.legalArea} onChange={e => setForm({ ...form, legalArea: e.target.value })} placeholder="Área" className="border rounded-xl p-3 text-sm" /><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className="border rounded-xl p-3 text-sm">{statuses.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className="border rounded-xl p-3 text-sm">{priorities.map(p => <option key={p.id} value={p.id}>Prioridade {p.label}</option>)}</select><input type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} className="border rounded-xl p-3 text-sm" /></div><div className="grid md:grid-cols-2 gap-3"><input value={form.processNumber} onChange={e => setForm({ ...form, processNumber: e.target.value })} placeholder="Número judicial (opcional)" className="border rounded-xl p-3 text-sm"/><input value={form.protocolNumber} onChange={e => setForm({ ...form, protocolNumber: e.target.value })} placeholder="Protocolo administrativo (opcional)" className="border rounded-xl p-3 text-sm"/></div><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} placeholder="Resumo e próximas providências internas" className="w-full border rounded-xl p-3 text-sm min-h-24"/><button disabled={saving} className="w-full py-3 bg-[#071B3A] text-white font-extrabold rounded-xl text-sm">{saving ? 'Salvando...' : edit ? 'Salvar alterações' : 'Criar processo e organizar documentos'}</button></form>;
  return <div className="space-y-5"><div className="rounded-3xl bg-gradient-to-r from-[#071B3A] to-[#0B3B78] text-white p-6 flex flex-col sm:flex-row gap-4 justify-between"><div><p className="text-[10px] font-extrabold text-blue-200 uppercase tracking-widest">Gestão do escritório</p><h1 className="text-2xl font-black font-heading mt-1">Processos e dossiês</h1><p className="text-sm text-blue-100 mt-2">Controle operacional de prazos, etapas, protocolo e documentos de cada cliente.</p></div><button onClick={() => { setForm(blankForm); setModal(true); }} className="self-start sm:self-center inline-flex items-center gap-2 bg-white text-[#071B3A] px-5 py-3 rounded-xl text-xs font-extrabold"><FolderPlus className="w-4 h-4" /> Novo processo</button></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-bold text-slate-400">Em andamento</p><p className="text-2xl font-black text-[#071B3A]">{processes.filter(p => !['CONCLUIDO','EM_TRIAGEM'].includes(p.status)).length}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-bold text-slate-400">Para protocolar</p><p className="text-2xl font-black text-amber-600">{processes.filter(p => p.status === 'PRONTO_PARA_PROTOCOLAR').length}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-bold text-slate-400">Prazos vencidos</p><p className="text-2xl font-black text-rose-600">{processes.filter(overdue).length}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-bold text-slate-400">Dossiês ativos</p><p className="text-2xl font-black text-blue-600">{processes.filter(p => p.status !== 'CONCLUIDO').length}</p></div></div>
    <div className="bg-white border rounded-2xl p-3 flex flex-col md:flex-row gap-2"><div className="flex-1 relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por cliente, título ou número" className="w-full pl-9 p-2.5 border rounded-xl text-sm"/></div><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="border rounded-xl p-2.5 text-sm"><option value="ALL">Todas as etapas</option>{statuses.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></div>
    {loading ? <div className="p-12 text-center"><Loader2 className="animate-spin w-6 h-6 text-blue-600 mx-auto" /></div> : visible.length === 0 ? <div className="bg-white border rounded-3xl p-12 text-center"><BriefcaseBusiness className="w-10 h-10 text-slate-300 mx-auto mb-3"/><h2 className="font-bold text-[#071B3A]">Nenhum processo encontrado</h2><p className="text-sm text-slate-500 mt-1">Os documentos assinados podem ser organizados em um dossiê nesta área.</p></div> : <div className="grid xl:grid-cols-2 gap-4">{visible.map(p => <button key={p.id} onClick={() => setSelected(p)} className="text-left bg-white border hover:border-blue-400 rounded-3xl p-5 transition-colors"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex gap-2 items-center"><span className="text-[10px] font-extrabold uppercase text-blue-700">{statusLabel(p.status)}</span><span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${priority(p.priority).color}`}>{priority(p.priority).label}</span></div><h2 className="font-heading font-black text-[#071B3A] mt-1 truncate">{p.title}</h2><p className="text-xs text-slate-500 mt-1 flex items-center gap-1"><User className="w-3 h-3"/>{p.client.name}</p></div><span className="rounded-xl bg-blue-50 text-blue-700 h-fit px-3 py-1 text-xs font-bold">{p.documents.length} PDFs</span></div><div className="grid grid-cols-2 gap-2 mt-4 pt-3 border-t text-xs text-slate-600"><span>{p.processNumber || p.protocolNumber || 'Sem protocolo'}</span><span className={`text-right ${overdue(p) ? 'font-bold text-rose-600' : ''}`}>{p.dueDate ? `Prazo: ${new Date(p.dueDate).toLocaleDateString('pt-BR')}` : 'Sem prazo'}</span></div></button>)}</div>}
    {modal && <div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><div className="w-full max-w-2xl bg-white rounded-3xl p-6"><div className="flex justify-between mb-4"><div><h2 className="font-heading font-black text-[#071B3A] text-lg">Novo processo</h2><p className="text-xs text-slate-500">Os documentos assinados escolhidos serão preservados e vinculados ao dossiê.</p></div><button onClick={() => setModal(false)}><X/></button></div><ProcessForm/></div></div>}
    {selected && <div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-white rounded-3xl p-6 space-y-5"><div className="flex justify-between"><div><p className="text-[10px] font-bold text-blue-700 uppercase">Dossiê da cliente</p><h2 className="font-heading font-black text-[#071B3A]">{selected.title}</h2><p className="text-xs text-slate-500">{selected.client.name}</p></div><div className="flex gap-2"><button onClick={() => beginEdit(selected)} className="p-2 text-blue-700 border rounded-xl"><Pencil className="w-4 h-4"/></button><button onClick={() => setSelected(null)}><X/></button></div></div><div className="grid sm:grid-cols-3 gap-3"><div className="rounded-xl bg-slate-50 border p-3 text-xs"><b>Etapa</b><br/>{statusLabel(selected.status)}</div><div className="rounded-xl bg-slate-50 border p-3 text-xs"><b>Prioridade</b><br/>{priority(selected.priority).label}</div><div className={`rounded-xl border p-3 text-xs ${overdue(selected) ? 'bg-rose-50 border-rose-200 text-rose-800' : 'bg-slate-50'}`}><b>Próximo prazo</b><br/>{selected.dueDate ? new Date(selected.dueDate).toLocaleDateString('pt-BR') : 'Não definido'}</div></div><div className="text-sm border rounded-2xl p-4">{selected.processNumber && <p><b>Processo:</b> {selected.processNumber}</p>}{selected.protocolNumber && <p><b>Protocolo:</b> {selected.protocolNumber}</p>}{selected.notes && <p className="mt-2 text-slate-600">{selected.notes}</p>}</div><div><h3 className="text-xs font-extrabold uppercase text-[#071B3A]">Documentos vinculados</h3><div className="mt-2 space-y-2">{selected.documents.length ? selected.documents.map(d => <div key={d.id} className="border rounded-xl p-3 flex justify-between gap-2 text-sm"><span>{d.title}</span>{d.signedFileId && <a href={`/api/documents/${d.id}/download`} download className="text-emerald-700 font-bold text-xs flex items-center gap-1"><Download className="w-3.5 h-3.5"/>PDF</a>}</div>) : <p className="text-sm text-slate-500">Nenhum documento vinculado.</p>}</div></div><div><h3 className="text-xs font-extrabold uppercase text-[#071B3A]">Linha do tempo</h3><div className="mt-2 border-l-2 border-blue-100 ml-2 space-y-3">{selected.activities.map(a => <div key={a.id} className="pl-4 text-xs"><p className="font-bold text-slate-700">{a.description}</p><p className="text-slate-400">{new Date(a.createdAt).toLocaleString('pt-BR')}</p></div>)}</div></div><Link href="/documentos" className="block text-center py-3 border rounded-xl text-sm font-bold text-[#071B3A]">Abrir Central de Documentos</Link></div></div>}
    {editing && <div className="fixed inset-0 z-[60] bg-black/50 p-4 flex items-center justify-center"><div className="w-full max-w-2xl bg-white rounded-3xl p-6"><div className="flex justify-between mb-4"><h2 className="font-heading font-black text-[#071B3A]">Atualizar processo</h2><button onClick={() => setEditing(false)}><X/></button></div><ProcessForm edit/></div></div>}
  </div>;
}
