'use client';
// Área interna de gestão de processos.

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { BriefcaseBusiness, CheckCircle2, FileText, FolderPlus, Loader2, X, Download, User } from 'lucide-react';

type Process = { id: string; title: string; legalArea?: string; status: string; processNumber?: string; protocolNumber?: string; notes?: string; client: { id: string; name: string; cpfCnpj: string; phone?: string }; documents: Array<{ id: string; title: string; status: string; signedFileId?: string }>; createdAt: string };
type Client = { id: string; name: string; cpfCnpj: string };
const statuses = [{ id: 'EM_TRIAGEM', label: 'Em triagem' }, { id: 'DOCUMENTACAO_PENDENTE', label: 'Documentação pendente' }, { id: 'PRONTO_PARA_PROTOCOLAR', label: 'Pronto para protocolar' }, { id: 'PROTOCOLADO', label: 'Protocolado' }, { id: 'EM_ANDAMENTO', label: 'Em andamento' }, { id: 'CONCLUIDO', label: 'Concluído / arquivado' }];

export default function ProcessosPage() {
  const [processes, setProcesses] = useState<Process[]>([]); const [clients, setClients] = useState<Client[]>([]); const [availableDocuments, setAvailableDocuments] = useState<Array<{id:string;title:string;client?:{id:string};status:string}>>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [selected, setSelected] = useState<Process | null>(null);
  const [form, setForm] = useState({ clientId: '', title: '', legalArea: 'Previdenciário', status: 'EM_TRIAGEM', processNumber: '', protocolNumber: '', notes: '', documentIds: [] as string[] });
  const load = async () => { setLoading(true); const [p, c] = await Promise.all([fetch('/api/processos').then(r => r.json()), fetch('/api/clients').then(r => r.json())]); setProcesses(p.processes || []); setClients(c.clients || []); setLoading(false); };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!form.clientId) return void setAvailableDocuments([]); fetch('/api/documents').then(r => r.json()).then(d => setAvailableDocuments((d.documents || []).filter((item:any) => item.client?.id === form.clientId && item.status === 'CONCLUIDO'))); }, [form.clientId]);
  const signedDocuments = useMemo(() => selected ? [] : [], [selected]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch('/api/processos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) return alert(d.error); setModal(false); setForm({ clientId: '', title: '', legalArea: 'Previdenciário', status: 'EM_TRIAGEM', processNumber: '', protocolNumber: '', notes: '', documentIds: [] }); load(); };
  return <div className="space-y-5"><div className="rounded-3xl bg-gradient-to-r from-[#071B3A] to-[#0B3B78] text-white p-6 flex flex-col sm:flex-row gap-4 justify-between"><div><p className="text-[10px] font-extrabold text-blue-200 uppercase tracking-widest">Gestão do escritório</p><h1 className="text-2xl font-black font-heading mt-1">Processos e dossiês</h1><p className="text-sm text-blue-100 mt-2">Organize somente os atendimentos confirmados. Os documentos continuam preservados na Central de Documentos.</p></div><button onClick={() => setModal(true)} className="self-start sm:self-center inline-flex items-center gap-2 bg-white text-[#071B3A] px-5 py-3 rounded-xl text-xs font-extrabold"><FolderPlus className="w-4 h-4" /> Novo processo</button></div>
    <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{statuses.slice(0, 3).map(s => <div key={s.id} className="bg-white border border-slate-200 rounded-2xl p-4"><p className="text-[10px] font-bold uppercase text-slate-400">{s.label}</p><p className="text-2xl font-black text-[#071B3A] mt-1">{processes.filter(p => p.status === s.id).length}</p></div>)}</div>
    {loading ? <div className="p-12 text-center"><Loader2 className="animate-spin w-6 h-6 text-blue-600 mx-auto" /></div> : processes.length === 0 ? <div className="bg-white border border-slate-200 rounded-3xl p-12 text-center"><BriefcaseBusiness className="w-10 h-10 text-slate-300 mx-auto mb-3" /><h2 className="font-bold text-[#071B3A]">Nenhum processo organizado ainda</h2><p className="text-sm text-slate-500 mt-1">Crie o primeiro processo quando a documentação da cliente estiver confirmada.</p></div> : <div className="grid lg:grid-cols-2 gap-4">{processes.map(p => <button key={p.id} onClick={() => setSelected(p)} className="text-left bg-white border border-slate-200 hover:border-blue-400 rounded-3xl p-5 transition-colors"><div className="flex justify-between gap-3"><div><span className="text-[10px] font-extrabold uppercase text-blue-700">{statuses.find(s => s.id === p.status)?.label || p.status}</span><h2 className="font-heading font-black text-[#071B3A] mt-1">{p.title}</h2><p className="text-xs text-slate-500 mt-1 flex items-center gap-1"><User className="w-3 h-3" /> {p.client.name}</p></div><span className="rounded-xl bg-blue-50 text-blue-700 h-fit px-3 py-1 text-xs font-bold">{p.documents.length} PDFs</span></div><div className="mt-4 pt-3 border-t border-slate-100 text-xs text-slate-600">{p.processNumber ? `Processo: ${p.processNumber}` : p.protocolNumber ? `Protocolo: ${p.protocolNumber}` : 'Aguardando protocolo'}</div></button>)}</div>}
    {modal && <div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form onSubmit={create} className="w-full max-w-lg bg-white rounded-3xl p-6 space-y-4"><div className="flex justify-between"><div><h2 className="font-heading font-black text-[#071B3A] text-lg">Criar processo</h2><p className="text-xs text-slate-500">Vincule apenas o atendimento real da cliente.</p></div><button type="button" onClick={() => setModal(false)}><X /></button></div><select required value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })} className="w-full border rounded-xl p-3 text-sm"><option value="">Selecione a cliente</option>{clients.map(c => <option key={c.id} value={c.id}>{c.name} — {c.cpfCnpj}</option>)}</select><input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Ex.: BPC/LOAS — Maria Aparecida" className="w-full border rounded-xl p-3 text-sm"/><div className="grid grid-cols-2 gap-3"><input value={form.legalArea} onChange={e => setForm({ ...form, legalArea: e.target.value })} placeholder="Área" className="border rounded-xl p-3 text-sm"/><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className="border rounded-xl p-3 text-sm">{statuses.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></div><input value={form.processNumber} onChange={e => setForm({ ...form, processNumber: e.target.value })} placeholder="Número do processo (opcional)" className="w-full border rounded-xl p-3 text-sm"/><input value={form.protocolNumber} onChange={e => setForm({ ...form, protocolNumber: e.target.value })} placeholder="Número do protocolo (opcional)" className="w-full border rounded-xl p-3 text-sm"/><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} placeholder="Observações internas" className="w-full border rounded-xl p-3 text-sm min-h-20"/><button className="w-full py-3 bg-[#071B3A] text-white font-extrabold rounded-xl text-sm">Criar processo</button></form></div>}
    {selected && <div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><div className="w-full max-w-xl bg-white rounded-3xl p-6 space-y-4"><div className="flex justify-between"><div><p className="text-[10px] font-bold text-blue-700 uppercase">Dossiê do processo</p><h2 className="font-heading font-black text-[#071B3A]">{selected.title}</h2><p className="text-xs text-slate-500">{selected.client.name}</p></div><button onClick={() => setSelected(null)}><X /></button></div><div className="rounded-2xl bg-slate-50 border border-slate-200 p-4 text-sm"><b>Status:</b> {statuses.find(s => s.id === selected.status)?.label}<br/>{selected.processNumber && <><b>Processo:</b> {selected.processNumber}<br/></>}{selected.protocolNumber && <><b>Protocolo:</b> {selected.protocolNumber}</>}</div><div><h3 className="text-xs font-extrabold text-[#071B3A] uppercase">Documentos vinculados</h3><div className="mt-2 space-y-2">{selected.documents.length ? selected.documents.map(d => <div key={d.id} className="border rounded-xl p-3 flex justify-between gap-2 text-sm"><span>{d.title}</span>{d.signedFileId && <a href={`/api/documents/${d.id}/download`} download className="text-emerald-700 font-bold text-xs flex items-center gap-1"><Download className="w-3.5 h-3.5"/> PDF</a>}</div>) : <p className="text-sm text-slate-500">Nenhum documento vinculado ainda.</p>}</div></div><Link href="/documentos" className="block text-center py-3 border rounded-xl text-sm font-bold text-[#071B3A]">Ir para Central de Documentos</Link></div></div>}
  </div>;
}
