'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, Clock3, FileSignature, FolderKanban, HelpCircle, Plus, Send, Sparkles, Users } from 'lucide-react';

type Action = { id: string; type: 'urgent' | 'attention' | 'next'; label: string; title: string; detail: string; href: string; action: string };

export default function DashboardPage() {
  const [clients, setClients] = useState<any[]>([]);
  const [documents, setDocuments] = useState<any[]>([]);
  const [processes, setProcesses] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showGuide, setShowGuide] = useState(true);

  useEffect(() => {
    setShowGuide(localStorage.getItem('assinajur-dashboard-guide-hidden') !== 'true');
    Promise.all([fetch('/api/clients').then((response) => response.json()), fetch('/api/documents').then((response) => response.json()), fetch('/api/processos').then((response) => response.json())])
      .then(([clientData, documentData, processData]) => { setClients(clientData.clients || []); setDocuments(documentData.documents || []); setProcesses(processData.processes || []); })
      .finally(() => setLoading(false));
  }, []);

  const pendingDocuments = documents.filter((document) => !['CONCLUIDO', 'CANCELADO', 'EXPIRADO'].includes(document.status));
  const completedDocuments = documents.filter((document) => document.status === 'CONCLUIDO');
  const actions = useMemo<Action[]>(() => {
    const now = Date.now();
    return [
      ...pendingDocuments.slice(0, 3).map((document) => ({ id: `signature-${document.id}`, type: 'urgent' as const, label: 'ASSINATURA PENDENTE', title: `Acompanhe ${document.client?.name || 'o signatário'}`, detail: `${document.title} ainda precisa ser concluído.`, href: '/documentos', action: 'Ver assinatura' })),
      ...processes.filter((process) => process.dueDate && new Date(process.dueDate).getTime() - now <= 3 * 86400000).sort((left, right) => new Date(left.dueDate).getTime() - new Date(right.dueDate).getTime()).slice(0, 2).map((process) => ({ id: `deadline-${process.id}`, type: 'attention' as const, label: 'PRAZO PRÓXIMO', title: `Revise ${process.client?.name || 'o cliente'}`, detail: `${process.title} • ${new Date(process.dueDate).toLocaleDateString('pt-BR')}.`, href: '/processos', action: 'Abrir processo' })),
      ...processes.filter((process) => process.status === 'EM_TRIAGEM').slice(0, 2).map((process) => ({ id: `triage-${process.id}`, type: 'next' as const, label: 'PRÓXIMA ETAPA', title: `Avance o atendimento de ${process.client?.name || 'cliente'}`, detail: `${process.title} está aguardando definição.`, href: '/processos', action: 'Organizar caso' })),
    ].slice(0, 5);
  }, [pendingDocuments, processes]);
  const dismissGuide = () => { localStorage.setItem('assinajur-dashboard-guide-hidden', 'true'); setShowGuide(false); };

  return <main className="mx-auto max-w-7xl space-y-6 pb-10">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-blue-600">AssinaJur • escritório</p><h1 className="mt-1 font-heading text-2xl font-extrabold tracking-tight text-[#071B3A]">Central de operação</h1><p className="mt-1 text-sm text-slate-500">Tudo o que o escritório precisa decidir, acompanhar e concluir hoje.</p></div><div className="flex flex-wrap gap-2"><Link href="/clientes?novo=true" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-extrabold text-[#071B3A] hover:bg-slate-50"><Plus className="mr-1 inline h-4 w-4" />Novo cliente</Link><Link href="/documentos/novo" className="rounded-xl bg-[#071B3A] px-4 py-2.5 text-xs font-extrabold text-white shadow-md hover:bg-[#102a56]"><Send className="mr-1 inline h-4 w-4 text-[#d4af37]" />Nova assinatura</Link></div></header>

    {showGuide && <section className="rounded-2xl border border-blue-200 bg-blue-50/70 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><HelpCircle className="mt-0.5 h-5 w-5 shrink-0 text-blue-700" /><div><p className="text-sm font-extrabold text-[#071B3A]">Primeira vez no AssinaJur?</p><p className="mt-1 text-xs leading-relaxed text-slate-600">Comece pelo cliente, formalize os documentos e depois organize o caso em Processos. O sistema acompanha o restante.</p></div></div><button onClick={dismissGuide} className="text-xs font-bold text-blue-700 hover:underline">Ocultar guia</button></div><div className="mt-4 grid gap-2 md:grid-cols-3">{[{ n: '01', title: 'Cliente', text: 'Cadastre, localize ou complete os dados.', href: '/clientes?novo=true' }, { n: '02', title: 'Assinatura', text: 'Envie PDFs ou um kit em link seguro.', href: '/documentos/novo' }, { n: '03', title: 'Processo', text: 'Reúna documentos assinados e acompanhe o caso.', href: '/processos' }].map((item) => <Link key={item.n} href={item.href} className="rounded-xl border border-blue-100 bg-white px-4 py-3 hover:border-blue-300"><span className="text-[10px] font-extrabold text-blue-600">{item.n}</span><p className="mt-1 text-xs font-extrabold text-[#071B3A]">{item.title}</p><p className="mt-0.5 text-[11px] text-slate-500">{item.text}</p></Link>)}</div></section>}

    <section className="overflow-hidden rounded-[28px] bg-[#071B3A] text-white shadow-[0_24px_60px_rgba(7,27,58,.2)]"><div className="grid gap-8 p-6 lg:grid-cols-[1.1fr_.9fr] lg:p-8"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#d4af37]">Visão da carteira</p><h2 className="mt-3 max-w-xl font-heading text-2xl font-extrabold leading-tight">O escritório em ordem. Agora, foque somente no que exige sua decisão.</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-slate-300">Acompanhe as assinaturas, mantenha os clientes organizados e avance cada atendimento sem deixar atividades espalhadas.</p><div className="mt-6 flex gap-3"><Link href="/documentos/novo" className="rounded-xl bg-[#d4af37] px-5 py-3 text-xs font-extrabold text-[#071B3A]">Enviar documentos</Link><Link href="/kits/enviar" className="rounded-xl border border-white/20 px-5 py-3 text-xs font-extrabold text-white">Preparar kit jurídico</Link></div></div><div className="grid grid-cols-3 gap-3 self-end">{[{ label: 'Clientes', value: clients.length, note: 'na base' }, { label: 'Pendentes', value: pendingDocuments.length, note: 'assinaturas' }, { label: 'Processos', value: processes.length, note: 'em gestão' }].map((item) => <div key={item.label} className="rounded-2xl border border-white/10 bg-white/[.08] p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-300">{item.label}</p><p className="mt-2 font-heading text-3xl font-extrabold">{loading ? '—' : item.value}</p><p className="text-[11px] text-slate-300">{item.note}</p></div>)}</div></div></section>

    <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-blue-600">Prioridades automáticas</p><h2 className="font-heading text-lg font-extrabold text-[#071B3A]">O que fazer agora</h2></div><span className="text-xs font-semibold text-slate-500">Atualizado com a carteira do escritório</span></div>{actions.length ? <div className="divide-y divide-slate-100">{actions.map((action) => <Link key={action.id} href={action.href} className="group flex flex-col gap-3 px-6 py-4 hover:bg-slate-50 sm:flex-row sm:items-center"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${action.type === 'urgent' ? 'bg-rose-500' : action.type === 'attention' ? 'bg-amber-500' : 'bg-blue-500'}`} /><div className="min-w-0 flex-1"><p className={`text-[10px] font-extrabold tracking-widest ${action.type === 'urgent' ? 'text-rose-600' : action.type === 'attention' ? 'text-amber-700' : 'text-blue-600'}`}>{action.label}</p><p className="mt-0.5 text-sm font-extrabold text-[#071B3A]">{action.title}</p><p className="mt-0.5 text-xs text-slate-500">{action.detail}</p></div><span className="text-xs font-extrabold text-blue-700 group-hover:underline">{action.action} <ArrowRight className="inline h-3.5 w-3.5" /></span></Link>)}</div> : <div className="p-9 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-emerald-500" /><p className="mt-3 font-bold text-[#071B3A]">Nenhuma pendência crítica.</p><p className="mt-1 text-xs text-slate-500">Quando surgir uma assinatura pendente, prazo ou triagem, ela aparecerá aqui.</p></div>}</section>

    <section className="grid gap-4 md:grid-cols-3"><Link href="/documentos" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><FileSignature className="h-5 w-5 text-blue-600" /><p className="mt-5 text-sm font-extrabold text-[#071B3A]">Assinaturas</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Veja quem abriu, assinou ou precisa receber novo link.</p><span className="mt-4 block text-xs font-extrabold text-blue-700">Gerenciar assinaturas →</span></Link><Link href="/processos" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><FolderKanban className="h-5 w-5 text-blue-600" /><p className="mt-5 text-sm font-extrabold text-[#071B3A]">Processos</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Organize documentos, etapas e movimentações de cada atendimento.</p><span className="mt-4 block text-xs font-extrabold text-blue-700">Abrir carteira →</span></Link><Link href="/kits/enviar" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-blue-300"><Sparkles className="h-5 w-5 text-[#b58d18]" /><p className="mt-5 text-sm font-extrabold text-[#071B3A]">Kits jurídicos</p><p className="mt-1 text-xs leading-relaxed text-slate-500">Crie documentos padronizados para um cliente em uma única sessão.</p><span className="mt-4 block text-xs font-extrabold text-blue-700">Preparar kit →</span></Link></section>

    <section className="rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-slate-500">Atividade recente</p><h2 className="font-heading text-lg font-extrabold text-[#071B3A]">Últimos documentos</h2></div><Link href="/documentos" className="text-xs font-extrabold text-blue-700">Ver todos</Link></div><div className="mt-4 divide-y divide-slate-100">{documents.slice(0, 4).map((document) => <Link key={document.id} href="/documentos" className="flex items-center gap-3 py-3 hover:bg-slate-50"><div className={`h-2 w-2 rounded-full ${document.status === 'CONCLUIDO' ? 'bg-emerald-500' : 'bg-amber-500'}`} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold text-[#071B3A]">{document.title}</p><p className="mt-0.5 text-[11px] text-slate-500">{document.client?.name || 'Documento avulso'} • {String(document.status).replaceAll('_', ' ')}</p></div><Clock3 className="h-4 w-4 text-slate-300" /></Link>)}{!documents.length && <p className="py-8 text-center text-xs text-slate-500">Nenhum documento criado ainda. Comece uma nova assinatura quando estiver pronto.</p>}</div></section>
  </main>;
}
